CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SLEEP=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_CONN_SHOW_USB=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=70
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=20
